#!/bin/bash
# ============================================================
# AETHERIA Security Platform — start.sh
#
# ONE command to rule them all. Bulletproof, idempotent, zero manual steps.
#
#   ./start.sh          → full local install + run (production build)
#   ./start.sh dev      → install + run in dev mode (hot reload)
#   ./start.sh docker   → docker compose up (fully autonomous stack)
#   ./start.sh update   → git pull + reinstall + restart
#
# What it does (local mode):
#   1. Verifies Node.js >= 20 (auto-installs via nvm if missing)
#   2. Installs dependencies (npm ci, falls back to npm install)
#   3. Ensures .env exists (auto-generates secrets)
#   4. Starts PostgreSQL (docker if available, else expects existing)
#   5. Applies Prisma schema + seeds catalog (idempotent)
#   6. Builds (prod) and starts the server
#
# Every step is safe to re-run. Failure at any step prints exactly what to fix.
# ============================================================

set -euo pipefail

MODE="${1:-prod}"
APP_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$APP_DIR"

# ---------- Colors ----------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[ OK ]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[FAIL]${NC} $*"; }
die()   { err "$*"; exit 1; }

# ---------- Helpers ----------
gen_hex()  { openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -A n -t x2 | tr -d ' \n'; }
gen_b64()  { openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '\n'; }

# ============================================================
# DOCKER MODE — fully autonomous, no local Node needed
# ============================================================
if [ "$MODE" = "docker" ]; then
  info "Docker mode — building & starting full stack (app + postgres + redis)..."

  command -v docker >/dev/null 2>&1 || die "Docker not found. Install: https://docs.docker.com/get-docker/"
  docker compose version >/dev/null 2>&1 || die "Docker Compose plugin not found. Update Docker Desktop or install the compose plugin."

  # Ensure .env exists with a DB password (compose requires it)
  if [ ! -f .env ]; then
    DB_PASS="$(gen_hex | head -c 24)"
    cat > .env <<EOF
DB_PASSWORD=$DB_PASS
NEXTAUTH_URL=http://localhost:3000
EOF
    ok ".env created with auto-generated DB_PASSWORD"
  fi

  docker compose up -d --build
  ok "Stack running."
  echo ""
  info "=========================================="
  info "  AETHERIA:  http://localhost:3000"
  info "  Logs:      docker compose logs -f app"
  info "  Stop:      docker compose down"
  info "  First run: open the URL and complete the"
  info "             setup wizard (admin + AI key)."
  info "=========================================="
  exit 0
fi

# ============================================================
# UPDATE MODE — pull latest + reinstall + restart
# ============================================================
if [ "$MODE" = "update" ]; then
  info "Pulling latest code..."
  git pull --ff-only || warn "git pull failed (not a git repo or conflicts) — continuing with current code"
  MODE="prod"
fi

# ============================================================
# LOCAL MODE — install everything, then run
# ============================================================

# ---------- 1. Node.js ----------
info "Checking Node.js (need >= 20)..."
if ! command -v node >/dev/null 2>&1; then
  warn "Node.js not found — trying nvm..."
  if [ -s "$HOME/.nvm/nvm.sh" ]; then
    # shellcheck disable=SC1091
    . "$HOME/.nvm/nvm.sh"
    nvm install 20 >/dev/null 2>&1 && nvm use 20 >/dev/null 2>&1
  fi
  command -v node >/dev/null 2>&1 || die "Node.js >= 20 required. Install: https://nodejs.org (or run: ./start.sh docker)"
fi
NODE_MAJOR="$(node -v | sed 's/v//' | cut -d. -f1)"
[ "$NODE_MAJOR" -ge 20 ] || die "Node.js >= 20 required (found $(node -v)). Or run: ./start.sh docker"
ok "Node.js $(node -v)"

# ---------- 2. Dependencies ----------
info "Installing dependencies..."
if [ -f package-lock.json ]; then
  npm ci --no-audit --no-fund 2>/dev/null || { warn "npm ci failed — falling back to npm install"; npm install --no-audit --no-fund; }
else
  npm install --no-audit --no-fund
fi
ok "Dependencies installed"

# ---------- 3. Environment (.env) ----------
# Next.js loads .env.local with top priority — respect it if present.
ENV_FILE=".env"
[ -f .env.local ] && ENV_FILE=".env.local"

if [ ! -f "$ENV_FILE" ] && [ ! -f .env ]; then
  info "Creating .env with auto-generated secrets..."
  cat > .env <<EOF
# Auto-generated by start.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=postgresql://aetheria:aetheria@localhost:5432/aetheriadb
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=$(gen_b64)
ENCRYPTION_KEY=$(gen_hex)
NODE_ENV=production
EOF
  ok ".env created"
else
  ok "Using existing $ENV_FILE"
fi

# Export env for prisma CLI (prisma reads .env; .env.local needs manual export)
set -a
[ -f .env ] && . ./.env
[ -f .env.local ] && . ./.env.local
set +a

# ---------- 4. PostgreSQL ----------
info "Checking PostgreSQL..."
DB_HOST="$(echo "$DATABASE_URL" | sed -E 's|.*@([^:/]+).*|\1|')"
if [ "$DB_HOST" = "localhost" ] || [ "$DB_HOST" = "127.0.0.1" ]; then
  if command -v docker >/dev/null 2>&1; then
    if ! docker ps --format '{{.Names}}' 2>/dev/null | grep -q '^aetheria-db-local$'; then
      info "Starting local PostgreSQL container (aetheria-db-local)..."
      DB_PASS="$(echo "$DATABASE_URL" | sed -E 's|.*://[^:]+:([^@]+)@.*|\1|')"
      DB_NAME="$(echo "$DATABASE_URL" | sed -E 's|.*/([^?]+).*|\1|')"
      docker run -d --name aetheria-db-local \
        -e POSTGRES_USER=aetheria -e POSTGRES_PASSWORD="$DB_PASS" -e POSTGRES_DB="$DB_NAME" \
        -p 5432:5432 -v aetheria-pgdata:/var/lib/postgresql/data \
        postgres:16-alpine >/dev/null 2>&1 || warn "Could not start postgres container (maybe already running on 5432)"
    fi
  fi
fi
# Wait for DB
info "Waiting for database to accept connections..."
TRIES=0
until node -e "const{PrismaClient}=require('@prisma/client');const p=new PrismaClient();p.\$connect().then(()=>process.exit(0)).catch(()=>process.exit(1))" >/dev/null 2>&1; do
  TRIES=$((TRIES+1))
  [ "$TRIES" -ge 45 ] && die "Database not reachable. Check DATABASE_URL in .env (or run: ./start.sh docker)"
  sleep 2
done
ok "Database ready"

# ---------- 5. Schema + Seeds ----------
info "Applying database schema (prisma db push — idempotent)..."
npx prisma generate >/dev/null 2>&1
# --accept-data-loss: upgrades may drop obsolete tables (e.g. licenses from the
# old multi-tenant edition). Without it prisma hangs waiting for confirmation.
npx prisma db push --skip-generate --accept-data-loss 2>&1 | tail -2
info "Seeding catalog + security rules (idempotent)..."
npx tsx prisma/seed-catalog.ts >/dev/null 2>&1 || warn "seed-catalog failed (non-fatal)"
npx tsx scripts/seed-security-rules.ts >/dev/null 2>&1 || warn "seed-security-rules failed (non-fatal)"
npx tsx scripts/seed-bughunter.ts >/dev/null 2>&1 || true
ok "Database seeded"

# ---------- 6. Build + Run ----------
if [ "$MODE" = "dev" ]; then
  ok "Starting DEV server (hot reload)..."
  exec npm run dev
else
  info "Building production bundle (this can take a few minutes)..."
  NODE_OPTIONS="--max-old-space-size=2048" npm run build
  ok "Build complete"
  echo ""
  info "=========================================="
  info "  AETHERIA:  http://localhost:3000"
  info "  First run: complete the setup wizard"
  info "             (admin account + AI API key)."
  info "  Stop:      Ctrl+C"
  info "=========================================="
  exec npm run start
fi
