export const KOTLIN_FALSE_POSITIVES = [
  {
    language: "kotlin",
    pattern: "println\\(",
    description: "Print statements for debugging",
    reason: "println is commonly used for debugging in development",
    context: "development",
    cweIds: ["CWE-532"],
    examples: ['println("Debug: $data")', 'println(user)'],
  },
  {
    language: "kotlin",
    pattern: "lateinit\\s+var",
    description: "Late-initialized properties",
    reason: "Standard Kotlin pattern for dependency injection",
    context: "dependency-injection",
    cweIds: ["CWE-476"],
    examples: ['lateinit var userService: UserService', '@Autowired lateinit var repository: Repository'],
  },
  {
    language: "kotlin",
    pattern: "!!",
    description: "Not-null assertion operator",
    reason: "Safe when developer knows value is not null",
    context: "controlled",
    cweIds: ["CWE-476"],
    examples: ['val user = findUser()!!', 'config.getValue("key")!!'],
  },
  {
    language: "kotlin",
    pattern: "\\?\\.",
    description: "Safe call operator",
    reason: "Kotlin null-safety operator",
    context: "null-safety",
    cweIds: ["CWE-476"],
    examples: ['user?.name', 'data?.process()'],
  },
  {
    language: "kotlin",
    pattern: "@Test",
    description: "JUnit test annotations",
    reason: "Standard testing framework",
    context: "testing",
    cweIds: ["CWE-489"],
    examples: ['@Test fun `should create user`() {}'],
  },
  // === Kotlin: Android & Spring ===
  {
    language: "kotlin",
    pattern: "@(RestController|Service|Repository|Component|Configuration|Bean)",
    description: "Spring Boot annotations",
    reason: "Standard Spring Framework dependency injection and routing annotations",
    context: "framework",
    cweIds: ["CWE-915", "CWE-862"],
    examples: ['@RestController class UserController', '@Service class AuthService'],
  },
  {
    language: "kotlin",
    pattern: "@(GetMapping|PostMapping|PutMapping|DeleteMapping|RequestMapping)",
    description: "Spring MVC route annotations",
    reason: "Standard Spring Web route definitions",
    context: "framework",
    cweIds: ["CWE-862"],
    examples: ['@GetMapping("/users/{id}")', '@PostMapping("/auth/login")'],
  },
  {
    language: "kotlin",
    pattern: "@(Entity|Table|Column|Id|GeneratedValue|ManyToOne|OneToMany)",
    description: "JPA/Hibernate entity annotations",
    reason: "Standard JPA ORM annotations with parameterized query generation",
    context: "safe-sql",
    cweIds: ["CWE-89"],
    examples: ['@Entity @Table(name = "users") class User', '@Id @GeneratedValue val id: Long'],
  },
  {
    language: "kotlin",
    pattern: "@(Composable|Preview|AndroidEntryPoint|HiltViewModel)",
    description: "Jetpack Compose / Hilt DI annotations",
    reason: "Standard Android Jetpack Compose UI and Hilt dependency injection",
    context: "framework",
    cweIds: ["CWE-915"],
    examples: ['@Composable fun Greeting(name: String)', '@HiltViewModel class MainViewModel @Inject constructor()'],
  },
  {
    language: "kotlin",
    pattern: "coroutineScope|launch|async|withContext|Dispatchers",
    description: "Kotlin coroutines",
    reason: "Standard Kotlin structured concurrency pattern, not a race condition",
    context: "concurrency",
    cweIds: ["CWE-362"],
    examples: ['viewModelScope.launch { fetchData() }', 'withContext(Dispatchers.IO) { db.query() }'],
  },
  {
    language: "kotlin",
    pattern: "Log\\.(d|i|w|e|v)\\(|Timber\\.",
    description: "Android logging (Logcat/Timber)",
    reason: "Standard Android logging removed in release builds via ProGuard/R8",
    context: "logging",
    cweIds: ["CWE-532"],
    examples: ['Log.d("TAG", "Value: $value")', 'Timber.d("User: %s", userId)'],
  },
  {
    language: "kotlin",
    pattern: "MessageDigest|SecretKey|KeyGenerator|Cipher\\.getInstance",
    description: "Java/Kotlin crypto APIs",
    reason: "Standard JCA cryptographic APIs with AES-256/SHA-256 are secure",
    context: "cryptography",
    cweIds: ["CWE-327", "CWE-328"],
    examples: ['MessageDigest.getInstance("SHA-256")', 'Cipher.getInstance("AES/GCM/NoPadding")'],
  },
  {
    language: "kotlin",
    pattern: "@(Validated|Valid)|BindingResult|@Size|@NotBlank|@Email",
    description: "Spring validation annotations",
    reason: "Standard Bean Validation (JSR-380) for input validation",
    context: "validation",
    cweIds: ["CWE-20"],
    examples: ['@Valid @RequestBody dto: CreateUserDto', '@field:Email val email: String'],
  },
  {
    language: "kotlin",
    pattern: "data class|sealed class|enum class|object\\s+\\w+",
    description: "Kotlin class types",
    reason: "Standard Kotlin language features for type-safe modeling",
    context: "language-feature",
    cweIds: ["CWE-704"],
    examples: ['data class User(val id: String, val name: String)', 'sealed class Result'],
  },
];
