export const SWIFT_FALSE_POSITIVES = [
  {
    language: "swift",
    pattern: "print\\(",
    description: "Print statements for debugging",
    reason: "print is commonly used for debugging",
    context: "development",
    cweIds: ["CWE-532"],
    examples: ['print("Debug: \\(data)")', 'print(user)'],
  },
  {
    language: "swift",
    pattern: "guard\\s+let",
    description: "Guard statements for unwrapping",
    reason: "Standard Swift pattern for safe unwrapping",
    context: "null-safety",
    cweIds: ["CWE-476"],
    examples: ['guard let user = user else { return }', 'guard let data = data else { throw Error }'],
  },
  {
    language: "swift",
    pattern: "if\\s+let",
    description: "Optional binding",
    reason: "Standard Swift pattern for safe unwrapping",
    context: "null-safety",
    cweIds: ["CWE-476"],
    examples: ['if let user = user { }', 'if let data = try? decode() { }'],
  },
  {
    language: "swift",
    pattern: "\\?\\?",
    description: "Nil-coalescing operator",
    reason: "Swift null-safety operator",
    context: "null-safety",
    cweIds: ["CWE-476"],
    examples: ['let name = user?.name ?? "Unknown"', 'value ?? defaultValue'],
  },
  {
    language: "swift",
    pattern: "@Published|@State|@Binding",
    description: "SwiftUI property wrappers",
    reason: "Standard SwiftUI patterns",
    context: "framework",
    cweIds: ["CWE-915"],
    examples: ['@Published var users: [User]', '@State private var isLoading = false'],
  },
  // === Swift: iOS/macOS Framework Patterns ===
  {
    language: "swift",
    pattern: "@(ObservableObject|StateObject|EnvironmentObject|ObservedObject|FetchRequest)",
    description: "SwiftUI data flow property wrappers",
    reason: "Standard SwiftUI reactive data flow patterns",
    context: "framework",
    cweIds: ["CWE-915"],
    examples: ['@StateObject private var vm = ViewModel()', '@EnvironmentObject var session: Session'],
  },
  {
    language: "swift",
    pattern: "URLSession|URLRequest|URLComponents|URL\\(",
    description: "Foundation networking APIs",
    reason: "Standard Apple networking framework with built-in TLS and certificate pinning support",
    context: "framework",
    cweIds: ["CWE-319", "CWE-295"],
    examples: ['let (data, _) = try await URLSession.shared.data(from: url)', 'var request = URLRequest(url: url)'],
  },
  {
    language: "swift",
    pattern: "Keychain|SecItem|kSecClass|kSecAttr",
    description: "iOS Keychain Services",
    reason: "Apple Keychain is the secure credential storage mechanism for iOS/macOS",
    context: "cryptography",
    cweIds: ["CWE-312", "CWE-922"],
    examples: ['SecItemAdd(query as CFDictionary, nil)', 'kSecClassGenericPassword'],
  },
  {
    language: "swift",
    pattern: "CryptoKit|CommonCrypto|CC_SHA|SecKey|CCCrypt",
    description: "Apple CryptoKit / CommonCrypto",
    reason: "Apple's cryptographic frameworks with AES-GCM, SHA-256, and Secure Enclave support",
    context: "cryptography",
    cweIds: ["CWE-327", "CWE-328"],
    examples: ['let hash = SHA256.hash(data: data)', 'let sealed = try AES.GCM.seal(plaintext, using: key)'],
  },
  {
    language: "swift",
    pattern: "CoreData|NSManagedObject|@FetchRequest|NSPredicate",
    description: "Core Data / SwiftData ORM",
    reason: "Apple's persistence framework with parameterized predicates",
    context: "safe-sql",
    cweIds: ["CWE-89"],
    examples: ['NSPredicate(format: "email == %@", email)', '@FetchRequest var users: FetchedResults<User>'],
  },
  {
    language: "swift",
    pattern: "Task\\s*\\{|async\\s+func|await\\s+|actor\\s+",
    description: "Swift structured concurrency",
    reason: "Swift async/await and actors provide safe concurrency by design",
    context: "concurrency",
    cweIds: ["CWE-362"],
    examples: ['Task { await fetchData() }', 'actor DataService { func load() async {} }'],
  },
  {
    language: "swift",
    pattern: "os_log|Logger\\(|NSLog|os\\.Logger",
    description: "Apple unified logging",
    reason: "Apple's unified logging system with privacy controls (redacts sensitive data by default)",
    context: "logging",
    cweIds: ["CWE-532"],
    examples: ['let logger = Logger(subsystem: "com.app", category: "network")', 'os_log("User: %{private}@", userId)'],
  },
  {
    language: "swift",
    pattern: "@(MainActor|Sendable|unchecked Sendable)",
    description: "Swift concurrency safety annotations",
    reason: "Swift concurrency safety markers that enforce thread-safety at compile time",
    context: "concurrency",
    cweIds: ["CWE-362", "CWE-567"],
    examples: ['@MainActor class ViewModel: ObservableObject', 'struct Config: Sendable {}'],
  },
  {
    language: "swift",
    pattern: "Codable|Decodable|Encodable|JSONDecoder|JSONEncoder",
    description: "Swift Codable protocol",
    reason: "Type-safe serialization with compile-time schema enforcement",
    context: "validation",
    cweIds: ["CWE-502", "CWE-20"],
    examples: ['let user = try JSONDecoder().decode(User.self, from: data)', 'struct User: Codable {}'],
  },
  {
    language: "swift",
    pattern: "XCTest|@testable|XCTAssert",
    description: "XCTest framework",
    reason: "Standard Apple testing framework",
    context: "testing",
    cweIds: ["CWE-489"],
    examples: ['class UserTests: XCTestCase { func testCreate() {} }', 'XCTAssertEqual(result, expected)'],
  },
];
