export const SCALA_FALSE_POSITIVES = [
  {
    language: "scala",
    pattern: "println\\(",
    description: "Print statements for debugging",
    reason: "println is commonly used for debugging",
    context: "development",
    cweIds: ["CWE-532"],
    examples: ['println(s"Debug: $data")', 'println(user)'],
  },
  {
    language: "scala",
    pattern: "Option\\[",
    description: "Option type for null-safety",
    reason: "Standard Scala pattern for handling nulls",
    context: "null-safety",
    cweIds: ["CWE-476"],
    examples: ['def findUser(id: String): Option[User]', 'val name: Option[String] = user.name'],
  },
  {
    language: "scala",
    pattern: "\\.get",
    description: "Option.get in controlled contexts",
    reason: "Safe when developer knows Option is Some",
    context: "controlled",
    cweIds: ["CWE-476"],
    examples: ['config.get("key").get', 'Some(value).get'],
  },
  {
    language: "scala",
    pattern: "implicit\\s+",
    description: "Implicit parameters and conversions",
    reason: "Standard Scala language feature",
    context: "language-feature",
    cweIds: ["CWE-915"],
    examples: ['implicit val ec: ExecutionContext', 'implicit def stringToInt(s: String): Int'],
  },
  {
    language: "scala",
    pattern: "case class",
    description: "Case classes",
    reason: "Standard Scala data structures",
    context: "language-feature",
    cweIds: ["CWE-1164"],
    examples: ['case class User(id: String, name: String)', 'case object Empty'],
  },
  // === Scala: Play Framework / Akka / Spark ===
  {
    language: "scala",
    pattern: "Action\\.|Action\\(|Action\\.async",
    description: "Play Framework action builders",
    reason: "Standard Play Framework HTTP action handlers with built-in CSRF protection",
    context: "framework",
    cweIds: ["CWE-862", "CWE-352"],
    examples: ['def index = Action { Ok(views.html.index()) }', 'def create = Action.async { request => }'],
  },
  {
    language: "scala",
    pattern: "ActorSystem|Actor\\[|Behavior|spawn|ActorRef",
    description: "Akka/Pekko actor system",
    reason: "Standard actor model concurrency with message-passing isolation",
    context: "concurrency",
    cweIds: ["CWE-362"],
    examples: ['val system = ActorSystem("mySystem")', 'val ref = system.spawn(behavior, "worker")'],
  },
  {
    language: "scala",
    pattern: "Future\\.|Promise\\.|ExecutionContext|import.*concurrent",
    description: "Scala Future/Promise concurrency",
    reason: "Standard Scala asynchronous programming with ExecutionContext isolation",
    context: "concurrency",
    cweIds: ["CWE-362"],
    examples: ['Future { computeExpensive() }', 'for { a <- futureA; b <- futureB } yield a + b'],
  },
  {
    language: "scala",
    pattern: "SparkSession|RDD|DataFrame|Dataset|\\.toDF|\\.rdd",
    description: "Apache Spark data processing",
    reason: "Standard Spark distributed data processing with typed DataSets",
    context: "framework",
    cweIds: ["CWE-915"],
    examples: ['val spark = SparkSession.builder().getOrCreate()', 'df.filter($"age" > 21).show()'],
  },
  {
    language: "scala",
    pattern: "Slick|doobie|Anorm|JDBC|PreparedStatement",
    description: "Scala database libraries",
    reason: "Functional database libraries with parameterized query support",
    context: "safe-sql",
    cweIds: ["CWE-89"],
    examples: ['db.run(users.filter(_.id === userId).result)', 'sql"SELECT * FROM users WHERE id = $id".query[User]'],
  },
  {
    language: "scala",
    pattern: "Either\\[|Try\\[|Validated\\[|IO\\[|ZIO\\[|Task\\[",
    description: "Scala effect types and error handling",
    reason: "Standard functional error handling that prevents unhandled exceptions",
    context: "error-handling",
    cweIds: ["CWE-755"],
    examples: ['def process: Either[AppError, Result]', 'ZIO.attempt(unsafeOp).catchAll(handleError)'],
  },
  {
    language: "scala",
    pattern: "@(Inject|Singleton|Provides|Named)",
    description: "Dependency injection annotations (Guice/CDI)",
    reason: "Standard DI container annotations for Scala/Java applications",
    context: "framework",
    cweIds: ["CWE-915"],
    examples: ['@Inject() (repo: UserRepository)', '@Singleton class AppService @Inject() ()'],
  },
  {
    language: "scala",
    pattern: "\\.map\\(|\\.flatMap\\(|\\.filter\\(|\\.fold|\\.reduce|\\.collect",
    description: "Scala collection operations",
    reason: "Standard functional collection transformations",
    context: "language-feature",
    cweIds: ["CWE-1164"],
    examples: ['users.map(_.name)', 'items.filter(_.isActive).fold(0)(_ + _.count)'],
  },
];
