/**
 * MITRE CWE Top 25 2025 - Real Data
 * Source: https://cwe.mitre.org/top25/archive/2025/2025_cwe_top25.html
 * Published: January 2026
 * Based on 39,080 CVE Records
 */

export const CWE_TOP_25_2025 = [
  {
    rank: 1,
    cweId: "CWE-79",
    name: "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
    kevCount: 7,
    category: "Web Application",
    severity: "HIGH" as const,
  },
  {
    rank: 2,
    cweId: "CWE-89",
    name: "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
    kevCount: 4,
    category: "Web Application",
    severity: "CRITICAL" as const,
  },
  {
    rank: 3,
    cweId: "CWE-352",
    name: "Cross-Site Request Forgery (CSRF)",
    kevCount: 0,
    category: "Web Application",
    severity: "MEDIUM" as const,
  },
  {
    rank: 4,
    cweId: "CWE-862",
    name: "Missing Authorization",
    kevCount: 0,
    category: "Authorization",
    severity: "HIGH" as const,
  },
  {
    rank: 5,
    cweId: "CWE-787",
    name: "Out-of-bounds Write",
    kevCount: 12,
    category: "Memory Safety",
    severity: "CRITICAL" as const,
  },
  {
    rank: 6,
    cweId: "CWE-22",
    name: "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
    kevCount: 10,
    category: "File System",
    severity: "HIGH" as const,
  },
  {
    rank: 7,
    cweId: "CWE-416",
    name: "Use After Free",
    kevCount: 14,
    category: "Memory Safety",
    severity: "CRITICAL" as const,
  },
  {
    rank: 8,
    cweId: "CWE-125",
    name: "Out-of-bounds Read",
    kevCount: 3,
    category: "Memory Safety",
    severity: "HIGH" as const,
  },
  {
    rank: 9,
    cweId: "CWE-78",
    name: "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
    kevCount: 20,
    category: "Command Injection",
    severity: "CRITICAL" as const,
  },
  {
    rank: 10,
    cweId: "CWE-94",
    name: "Improper Control of Generation of Code ('Code Injection')",
    kevCount: 7,
    category: "Code Injection",
    severity: "CRITICAL" as const,
  },
  {
    rank: 11,
    cweId: "CWE-120",
    name: "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')",
    kevCount: 0,
    category: "Memory Safety",
    severity: "CRITICAL" as const,
  },
  {
    rank: 12,
    cweId: "CWE-434",
    name: "Unrestricted Upload of File with Dangerous Type",
    kevCount: 4,
    category: "File Upload",
    severity: "HIGH" as const,
  },
  {
    rank: 13,
    cweId: "CWE-476",
    name: "NULL Pointer Dereference",
    kevCount: 0,
    category: "Memory Safety",
    severity: "MEDIUM" as const,
  },
  {
    rank: 14,
    cweId: "CWE-121",
    name: "Stack-based Buffer Overflow",
    kevCount: 4,
    category: "Memory Safety",
    severity: "CRITICAL" as const,
  },
  {
    rank: 15,
    cweId: "CWE-502",
    name: "Deserialization of Untrusted Data",
    kevCount: 11,
    category: "Deserialization",
    severity: "CRITICAL" as const,
  },
  {
    rank: 16,
    cweId: "CWE-122",
    name: "Heap-based Buffer Overflow",
    kevCount: 6,
    category: "Memory Safety",
    severity: "CRITICAL" as const,
  },
  {
    rank: 17,
    cweId: "CWE-863",
    name: "Incorrect Authorization",
    kevCount: 4,
    category: "Authorization",
    severity: "HIGH" as const,
  },
  {
    rank: 18,
    cweId: "CWE-20",
    name: "Improper Input Validation",
    kevCount: 2,
    category: "Input Validation",
    severity: "HIGH" as const,
  },
  {
    rank: 19,
    cweId: "CWE-284",
    name: "Improper Access Control",
    kevCount: 1,
    category: "Access Control",
    severity: "HIGH" as const,
  },
  {
    rank: 20,
    cweId: "CWE-200",
    name: "Exposure of Sensitive Information to an Unauthorized Actor",
    kevCount: 1,
    category: "Information Disclosure",
    severity: "MEDIUM" as const,
  },
  {
    rank: 21,
    cweId: "CWE-306",
    name: "Missing Authentication for Critical Function",
    kevCount: 11,
    category: "Authentication",
    severity: "CRITICAL" as const,
  },
  {
    rank: 22,
    cweId: "CWE-918",
    name: "Server-Side Request Forgery (SSRF)",
    kevCount: 0,
    category: "Web Application",
    severity: "HIGH" as const,
  },
  {
    rank: 23,
    cweId: "CWE-77",
    name: "Improper Neutralization of Special Elements used in a Command ('Command Injection')",
    kevCount: 2,
    category: "Command Injection",
    severity: "CRITICAL" as const,
  },
  {
    rank: 24,
    cweId: "CWE-639",
    name: "Authorization Bypass Through User-Controlled Key",
    kevCount: 0,
    category: "Authorization",
    severity: "HIGH" as const,
  },
  {
    rank: 25,
    cweId: "CWE-770",
    name: "Allocation of Resources Without Limits or Throttling",
    kevCount: 0,
    category: "Resource Management",
    severity: "MEDIUM" as const,
  },
];

export const CWE_DESCRIPTIONS: Record<string, { description: string; remediation: string; languages: string[] }> = {
  "CWE-79": {
    description: "The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output that is used as a web page that is served to other users.",
    remediation: "Use output encoding, validate input, implement Content Security Policy (CSP), use frameworks with built-in XSS protection.",
    languages: ["JavaScript", "TypeScript", "PHP", "Python", "Ruby", "Java", "C#"],
  },
  "CWE-89": {
    description: "The software constructs all or part of an SQL command using externally-influenced input from an upstream component, but it does not neutralize or incorrectly neutralizes special elements that could modify the intended SQL command.",
    remediation: "Use parameterized queries, prepared statements, ORM frameworks, input validation, least privilege database accounts.",
    languages: ["SQL", "JavaScript", "TypeScript", "PHP", "Python", "Ruby", "Java", "C#"],
  },
  "CWE-352": {
    description: "The web application does not, or can not, sufficiently verify whether a well-formed, valid, consistent request was intentionally provided by the user who submitted the request.",
    remediation: "Use anti-CSRF tokens, SameSite cookie attribute, verify Origin/Referer headers, require re-authentication for sensitive operations.",
    languages: ["JavaScript", "TypeScript", "PHP", "Python", "Ruby", "Java", "C#"],
  },
  "CWE-862": {
    description: "The software does not perform an authorization check when an actor attempts to access a resource or perform an action.",
    remediation: "Implement proper authorization checks, use role-based access control (RBAC), verify permissions on every request, deny by default.",
    languages: ["JavaScript", "TypeScript", "PHP", "Python", "Ruby", "Java", "C#", "Go"],
  },
  "CWE-787": {
    description: "The software writes data past the end, or before the beginning, of the intended buffer.",
    remediation: "Use safe string functions, bounds checking, memory-safe languages, AddressSanitizer, static analysis tools.",
    languages: ["C", "C++", "Assembly"],
  },
  "CWE-22": {
    description: "The software uses external input to construct a pathname that is intended to identify a file or directory that is located underneath a restricted parent directory, but the software does not properly neutralize special elements within the pathname.",
    remediation: "Validate and sanitize file paths, use whitelists, canonicalize paths, implement chroot jails, avoid user input in file paths.",
    languages: ["JavaScript", "TypeScript", "PHP", "Python", "Ruby", "Java", "C#", "Go"],
  },
  "CWE-416": {
    description: "Referencing memory after it has been freed can cause a program to crash, use unexpected values, or execute code.",
    remediation: "Use memory-safe languages, smart pointers, AddressSanitizer, static analysis, careful memory management.",
    languages: ["C", "C++"],
  },
  "CWE-125": {
    description: "The software reads data past the end, or before the beginning, of the intended buffer.",
    remediation: "Bounds checking, use safe functions, memory-safe languages, AddressSanitizer, fuzzing.",
    languages: ["C", "C++"],
  },
  "CWE-78": {
    description: "The software constructs all or part of an OS command using externally-influenced input from an upstream component, but it does not neutralize or incorrectly neutralizes special elements that could modify the intended OS command.",
    remediation: "Avoid system calls with user input, use APIs instead of shell commands, input validation, whitelisting, least privilege.",
    languages: ["JavaScript", "TypeScript", "PHP", "Python", "Ruby", "Java", "C#", "Go", "Bash"],
  },
  "CWE-94": {
    description: "The software constructs all or part of a code segment using externally-influenced input from an upstream component, but it does not neutralize or incorrectly neutralizes special elements that could modify the syntax or behavior of the intended code segment.",
    remediation: "Avoid eval() and similar functions, use safe parsing, input validation, sandboxing, code review.",
    languages: ["JavaScript", "TypeScript", "PHP", "Python", "Ruby"],
  },
};
